CREATE TABLE [etl].[temp_dimcustomer]
(
[RowIndex] [bigint] NULL,
[ETL__SourceSystem] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__SSID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__SSID_PATRON] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DimRepId] [int] NULL,
[IsCompany] [bit] NULL,
[CompanyName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prefix] [int] NULL,
[FirstName] [int] NULL,
[MiddleName] [int] NULL,
[LastName] [int] NULL,
[Suffix] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TicketCustomerClass] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[Status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CustomerId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VIPCode] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[IsVIP] [bit] NULL,
[Tag] [varchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountType] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[Keywords] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddDateTime] [datetime] NULL,
[SinceDate] [datetime] NULL,
[Birthday] [datetime] NULL,
[Email] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [int] NULL,
[AddressStreet1] [int] NULL,
[AddressStreet2] [int] NULL,
[AddressCity] [int] NULL,
[AddressState] [int] NULL,
[AddressZip] [int] NULL,
[AddressCountry] [int] NULL
)
GO
