IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\ameitin')
CREATE LOGIN [SSBCLOUD\ameitin] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\ameitin] FOR LOGIN [SSBCLOUD\ameitin] WITH DEFAULT_SCHEMA=[SSBCLOUD\ameitin]
GO
REVOKE CONNECT TO [SSBCLOUD\ameitin]
